services:
  app:
    container_name: app.${APP_NAME}
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
      - "${DIAG_PORT}:${DIAG_PORT}"
    environment:
      - DB_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_DATABASE}?sslmode=disable
      - API_PORT=${API_PORT}
      - DIAG_PORT=${DIAG_PORT}
      - HTTP_TIMEOUT=${HTTP_TIMEOUT}
      - IDLE_TIMEOUT=${IDLE_TIMEOUT}
      - SHUTDOWN_TIMEOUT=${SHUTDOWN_TIMEOUT}
      - DB_MAX_CONN=${DB_MAX_CONN}
      - DB_MAX_IDLE=${DB_MAX_IDLE}
      - DB_MAX_CONN_TIME=${DB_MAX_CONN_TIME}
      - DB_MAX_IDLE_TIME=${DB_MAX_IDLE_TIME}
      - REDIS_ADDRESS=${REDIS_HOST}:${REDIS_PORT}
    depends_on:
      - db
      - dbmate
      - kvrocks
    networks:
      - app

  db:
    container_name: db.${APP_NAME}
    image: postgres:17
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    networks:
      - app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
      interval: 1s
      timeout: 2s
      retries: 5
    restart: unless-stopped

  kvrocks:
    container_name: kvrocks.${APP_NAME}
    image: apache/kvrocks:2.14.0
    volumes:
      - kvrocks_data:/kvrocks_data
    ports:
      - '${REDIS_PORT}:6666'
    networks:
      - app
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "${REDIS_PORT}", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
    expose:
      - '${REDIS_PORT}'

  dbmate:
    container_name: dbmate.${APP_NAME}
    image: amacneil/dbmate:2.28
    entrypoint: ["dbmate", "up"]
    environment:
      - DATABASE_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_DATABASE}?sslmode=disable
    volumes:
      - ./db:/db
    depends_on:
      - db
    networks:
      - app

volumes:
  pg_data:
  kvrocks_data:

networks:
  app:
    driver: bridge