services:
  app:
    container_name: app.${APP_NAME}
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
      - "${DIAG_PORT}:${DIAG_PORT}"
    environment:
      - DB_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_DATABASE}?sslmode=disable
      - API_PORT=${API_PORT}
      - DIAG_PORT=${DIAG_PORT}
      - HTTP_TIMEOUT=${HTTP_TIMEOUT}
      - IDLE_TIMEOUT=${IDLE_TIMEOUT}
      - SHUTDOWN_TIMEOUT=${SHUTDOWN_TIMEOUT}
    depends_on:
      - db
      - flyway
    networks:
      - app

  db:
    container_name: db.${APP_NAME}
    image: postgres:17
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    networks:
      - app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
      interval: 1s
      timeout: 2s
      retries: 5
    restart: unless-stopped

  flyway:
    container_name: flyway.${APP_NAME}
    image: boxfuse/flyway:latest
    command: "-url=jdbc:postgresql://db:5432/${DB_DATABASE} -user=${DB_USERNAME} -password=${DB_PASSWORD} migrate"
    volumes:
      - ./db/migration:/flyway/sql
    depends_on:
      - db
    networks:
      - app

volumes:
  pg_data:

networks:
  app:
    driver: bridge